# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mindspy.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mindspy.proto',
  package='mindspy.protobufs',
  serialized_pb='\n\rmindspy.proto\x12\x11mindspy.protobufs\"\x19\n\tSeparator\x12\x0c\n\x04last\x18\x02 \x02(\x08\")\n\x05State\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x02(\r\x12\x0f\n\x07payload\x18\x02 \x02(\r\"/\n\x06Sample\x12\x10\n\x08sequence\x18\x01 \x02(\x04\x12\x13\n\x07payload\x18\x02 \x03(\x05\x42\x02\x10\x01\"\x1b\n\nGetSamples\x12\r\n\x05\x63ount\x18\x01 \x02(\r\"!\n\x08GetState\x12\x15\n\taddresses\x18\x01 \x03(\rB\x02\x10\x01\"4\n\x08SetState\x12(\n\x06states\x18\x01 \x03(\x0b\x32\x18.mindspy.protobufs.State\"\x0e\n\x0cGetModelName\"\x9a\x02\n\x07Request\x12\x11\n\ttimestamp\x18\x01 \x02(\x04\x12\r\n\x05reqid\x18\x02 \x02(\r\x12\x0e\n\x06module\x18\x03 \x01(\r\x12\x15\n\x06stream\x18\x04 \x01(\x08:\x05\x66\x61lse\x12\x31\n\ngetSamples\x18\x05 \x01(\x0b\x32\x1d.mindspy.protobufs.GetSamples\x12-\n\x08getState\x18\x06 \x01(\x0b\x32\x1b.mindspy.protobufs.GetState\x12-\n\x08setState\x18\x07 \x01(\x0b\x32\x1b.mindspy.protobufs.SetState\x12\x35\n\x0cgetModelName\x18\x08 \x01(\x0b\x32\x1f.mindspy.protobufs.GetModelName\"\xb8\x01\n\x08Response\x12\x11\n\ttimestamp\x18\x01 \x02(\x04\x12\r\n\x05reqid\x18\x02 \x02(\r\x12\x0e\n\x06module\x18\x03 \x01(\r\x12(\n\x06states\x18\x04 \x03(\x0b\x32\x18.mindspy.protobufs.State\x12*\n\x07samples\x18\x05 \x03(\x0b\x32\x19.mindspy.protobufs.Sample\x12\x11\n\tmodelName\x18\x06 \x01(\t\x12\x11\n\terror_msg\x18\x07 \x01(\tB\x1e\n\x15org.mindspy.protobufsB\x05Proto')




_SEPARATOR = _descriptor.Descriptor(
  name='Separator',
  full_name='mindspy.protobufs.Separator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='last', full_name='mindspy.protobufs.Separator.last', index=0,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=61,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='mindspy.protobufs.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='mindspy.protobufs.State.address', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='mindspy.protobufs.State.payload', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=63,
  serialized_end=104,
)


_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='mindspy.protobufs.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence', full_name='mindspy.protobufs.Sample.sequence', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='mindspy.protobufs.Sample.payload', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=106,
  serialized_end=153,
)


_GETSAMPLES = _descriptor.Descriptor(
  name='GetSamples',
  full_name='mindspy.protobufs.GetSamples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='mindspy.protobufs.GetSamples.count', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=155,
  serialized_end=182,
)


_GETSTATE = _descriptor.Descriptor(
  name='GetState',
  full_name='mindspy.protobufs.GetState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addresses', full_name='mindspy.protobufs.GetState.addresses', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=184,
  serialized_end=217,
)


_SETSTATE = _descriptor.Descriptor(
  name='SetState',
  full_name='mindspy.protobufs.SetState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='states', full_name='mindspy.protobufs.SetState.states', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=219,
  serialized_end=271,
)


_GETMODELNAME = _descriptor.Descriptor(
  name='GetModelName',
  full_name='mindspy.protobufs.GetModelName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=273,
  serialized_end=287,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='mindspy.protobufs.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='mindspy.protobufs.Request.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reqid', full_name='mindspy.protobufs.Request.reqid', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='module', full_name='mindspy.protobufs.Request.module', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stream', full_name='mindspy.protobufs.Request.stream', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='getSamples', full_name='mindspy.protobufs.Request.getSamples', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='getState', full_name='mindspy.protobufs.Request.getState', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='setState', full_name='mindspy.protobufs.Request.setState', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='getModelName', full_name='mindspy.protobufs.Request.getModelName', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=290,
  serialized_end=572,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='mindspy.protobufs.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='mindspy.protobufs.Response.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reqid', full_name='mindspy.protobufs.Response.reqid', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='module', full_name='mindspy.protobufs.Response.module', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='states', full_name='mindspy.protobufs.Response.states', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='samples', full_name='mindspy.protobufs.Response.samples', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modelName', full_name='mindspy.protobufs.Response.modelName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='mindspy.protobufs.Response.error_msg', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=575,
  serialized_end=759,
)

_SETSTATE.fields_by_name['states'].message_type = _STATE
_REQUEST.fields_by_name['getSamples'].message_type = _GETSAMPLES
_REQUEST.fields_by_name['getState'].message_type = _GETSTATE
_REQUEST.fields_by_name['setState'].message_type = _SETSTATE
_REQUEST.fields_by_name['getModelName'].message_type = _GETMODELNAME
_RESPONSE.fields_by_name['states'].message_type = _STATE
_RESPONSE.fields_by_name['samples'].message_type = _SAMPLE
DESCRIPTOR.message_types_by_name['Separator'] = _SEPARATOR
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
DESCRIPTOR.message_types_by_name['GetSamples'] = _GETSAMPLES
DESCRIPTOR.message_types_by_name['GetState'] = _GETSTATE
DESCRIPTOR.message_types_by_name['SetState'] = _SETSTATE
DESCRIPTOR.message_types_by_name['GetModelName'] = _GETMODELNAME
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

class Separator(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEPARATOR

  # @@protoc_insertion_point(class_scope:mindspy.protobufs.Separator)

class State(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATE

  # @@protoc_insertion_point(class_scope:mindspy.protobufs.State)

class Sample(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SAMPLE

  # @@protoc_insertion_point(class_scope:mindspy.protobufs.Sample)

class GetSamples(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETSAMPLES

  # @@protoc_insertion_point(class_scope:mindspy.protobufs.GetSamples)

class GetState(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETSTATE

  # @@protoc_insertion_point(class_scope:mindspy.protobufs.GetState)

class SetState(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETSTATE

  # @@protoc_insertion_point(class_scope:mindspy.protobufs.SetState)

class GetModelName(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETMODELNAME

  # @@protoc_insertion_point(class_scope:mindspy.protobufs.GetModelName)

class Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST

  # @@protoc_insertion_point(class_scope:mindspy.protobufs.Request)

class Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE

  # @@protoc_insertion_point(class_scope:mindspy.protobufs.Response)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\025org.mindspy.protobufsB\005Proto')
_SAMPLE.fields_by_name['payload'].has_options = True
_SAMPLE.fields_by_name['payload']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_GETSTATE.fields_by_name['addresses'].has_options = True
_GETSTATE.fields_by_name['addresses']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
